version: "3.9"
services:

  web:
    <<: &web
      # Image name is changed in production:
      image: "voxy-backend:dev"
      env_file: ./docker/config/.env
      build:
        context: .
        dockerfile: ./docker/config/Dockerfile
        cache_from:
          - "voxy-backend:dev"
          - "voxy-backend:latest"
          - "*"
        args:
          PROJECT_ENV: development
      platform:
        linux/x86_64
      ports:
        - "8000:8000"
      extra_hosts:
      - "host.docker.internal:host-gateway"

      tty: true
      restart: always

      networks:
        - webnet

    
    command: python manage.py runserver 0.0.0.0:8000



      


networks:
  # Network for your internals, use it by default:
  webnet: